import 'package:drift/drift.dart';

import '../app_database.dart';

class ExerciseSeedData {
  static Future<void> seed(AppDatabase db, {String locale = 'de'}) async {
    final dao = db.exerciseDao;
    if (await dao.hasExercises()) return;

    for (final e in _exercises) {
      final id = await dao.insertExercise(ExercisesCompanion.insert(
        name: e.localizedName(locale),
        nameKey: e.nameKey,
        instructions: Value(e.localizedInstructions(locale)),
        primaryMuscleGroup: e.muscleGroup,
        category: e.category,
        trackWeight: Value(e.trackWeight),
      ));
      for (final eq in e.equipment) {
        await dao.insertEquipment(ExerciseEquipmentCompanion.insert(
          exerciseId: id,
          equipmentType: eq.name,
        ));
      }
    }
  }

  static Future<void> seedMissing(AppDatabase db, {String locale = 'de'}) async {
    final dao = db.exerciseDao;
    for (final e in _exercises) {
      final existing = await dao.getByNameKey(e.nameKey);
      if (existing == null) {
        final id = await dao.insertExercise(ExercisesCompanion.insert(
          name: e.localizedName(locale),
          nameKey: e.nameKey,
          instructions: Value(e.localizedInstructions(locale)),
          primaryMuscleGroup: e.muscleGroup,
          category: e.category,
          trackWeight: Value(e.trackWeight),
        ));
        for (final eq in e.equipment) {
          await dao.insertEquipment(ExerciseEquipmentCompanion.insert(
            exerciseId: id,
            equipmentType: eq.name,
          ));
        }
      }
    }
  }

  /// Map of English name → German name for migration
  static const nameTranslations = {
    'Bench Press': 'Bankdrücken',
    'Incline Bench Press': 'Schrägbankdrücken',
    'Dumbbell Chest Press': 'Kurzhantel-Brustdrücken',
    'Cable Fly': 'Kabelzug-Flys',
    'Machine Chest Press': 'Maschinen-Brustpresse',
    'Push-ups': 'Liegestütze',
    'Barbell Row': 'Langhantel-Rudern',
    'Lat Pulldown': 'Latzug',
    'Seated Cable Row': 'Kabelrudern sitzend',
    'Dumbbell Row': 'Kurzhantel-Rudern',
    'Pull-ups': 'Klimmzüge',
    'T-Bar Row': 'T-Bar-Rudern',
    'Overhead Press': 'Schulterdrücken',
    'Lateral Raise': 'Seitheben',
    'Front Raise': 'Frontheben',
    'Face Pull': 'Face Pull',
    'Machine Shoulder Press': 'Maschinen-Schulterdrücken',
    'Barbell Curl': 'Langhantel-Curls',
    'Dumbbell Curl': 'Kurzhantel-Curls',
    'Hammer Curl': 'Hammer-Curls',
    'Cable Curl': 'Kabelzug-Curls',
    'Tricep Pushdown': 'Trizepsdrücken am Kabel',
    'Overhead Tricep Extension': 'Trizepsdrücken über Kopf',
    'Skull Crusher': 'Skull Crusher',
    'Dips': 'Dips',
    'Barbell Squat': 'Kniebeuge',
    'Leg Press': 'Beinpresse',
    'Leg Extension': 'Beinstrecken',
    'Lunges': 'Ausfallschritte',
    'Front Squat': 'Frontkniebeuge',
    'Romanian Deadlift': 'Rumänisches Kreuzheben',
    'Leg Curl': 'Beinbeuger',
    'Good Morning': 'Good Morning',
    'Nordic Curl': 'Nordic Curl',
    'Hip Thrust': 'Hip Thrust',
    'Cable Kickback': 'Kabelzug-Kickback',
    'Glute Bridge': 'Glute Bridge',
    'Standing Calf Raise': 'Wadenheben stehend',
    'Seated Calf Raise': 'Wadenheben sitzend',
    'Plank': 'Plank',
    'Cable Crunch': 'Kabelzug-Crunch',
    'Hanging Leg Raise': 'Beinheben hängend',
    'Ab Rollout': 'Ab Rollout',
    'Deadlift': 'Kreuzheben',
    'Clean & Press': 'Umsetzen & Drücken',
    "Farmer's Walk": 'Farmers Walk',
    'Treadmill Run': 'Laufband',
    'Rowing Machine': 'Rudergerät',
    'Stationary Bike': 'Ergometer',
    'Elliptical': 'Crosstrainer',
    'Incline Dumbbell Press': 'Schrägbank-Kurzhanteldrücken',
    'Dumbbell Fly': 'Kurzhantel-Flys',
    'Incline Dumbbell Fly': 'Schrägbank-Flys',
    'Decline Bench Press': 'Negativbankdrücken',
    'Preacher Curl': 'Preacher Curls',
    'Concentration Curl': 'Konzentrationscurls',
    'Arnold Press': 'Arnold Press',
    'Hyperextension': 'Hyperextensions',
    'Close Grip Bench Press': 'Enges Bankdrücken',
    'Tricep Kickback': 'Trizeps-Kickbacks',
    'Sumo Deadlift': 'Sumo-Kreuzheben',
    'Narrow Leg Press': 'Beinpresse eng',
    'Adductor Machine': 'Adduktoren-Maschine',
    'Abductor Machine': 'Abduktoren-Maschine',
    'Shrugs': 'Shrugs',
  };
}

enum _Eq {
  barbell,
  dumbbell,
  cable,
  machine,
  bodyweight,
  benchPress,
  latPulldown,
  legExtension,
  legCurl,
  seatedRow,
  shoulderPress,
  smithMachine,
  chestFly,
  rowingMachine,
  treadmill,
  stationaryBike,
  elliptical,
  bench,
  inclineBench,
  dipStation,
  pullUpBar,
  hyperextensionBench,
  preacherCurlBench,
}

class _ExDef {
  final String name;
  final String nameKey;
  final String? instructions;
  final String? nameEn;
  final String? instructionsEn;
  final String muscleGroup;
  final String category;
  final List<_Eq> equipment;
  final bool trackWeight;

  const _ExDef({
    required this.name,
    required this.nameKey,
    this.instructions,
    this.nameEn,
    this.instructionsEn,
    required this.muscleGroup,
    required this.category,
    required this.equipment,
    this.trackWeight = true,
  });

  String localizedName(String locale) =>
      locale == 'en' && nameEn != null ? nameEn! : name;

  String? localizedInstructions(String locale) =>
      locale == 'en' && instructionsEn != null ? instructionsEn : instructions;
}

const _exercises = [
  // Brust (6)
  _ExDef(
    name: 'Bankdrücken',
    nameEn: 'Bench Press',
    nameKey: 'bench_press',
    instructions: 'Flach auf Bank liegen, Stange etwas weiter als schulterbreit greifen, zur Brust senken und hochdrücken.',
    instructionsEn: 'Lie flat on bench, grip bar slightly wider than shoulder width, lower to chest and press up.',
    muscleGroup: 'chest',
    category: 'compound',
    equipment: [_Eq.barbell, _Eq.benchPress, _Eq.bench],
  ),
  _ExDef(
    name: 'Schrägbankdrücken',
    nameEn: 'Incline Bench Press',
    nameKey: 'incline_bench_press',
    instructions: 'Bank auf 30-45 Grad stellen, Stange von der oberen Brust drücken.',
    instructionsEn: 'Set bench to 30-45 degrees, press bar from upper chest.',
    muscleGroup: 'chest',
    category: 'compound',
    equipment: [_Eq.barbell, _Eq.benchPress, _Eq.inclineBench],
  ),
  _ExDef(
    name: 'Kurzhantel-Brustdrücken',
    nameEn: 'Dumbbell Chest Press',
    nameKey: 'dumbbell_chest_press',
    instructions: 'Flach liegen, Kurzhanteln von Brusthöhe mit neutralem Griff hochdrücken.',
    instructionsEn: 'Lie flat, press dumbbells up from chest height with neutral grip.',
    muscleGroup: 'chest',
    category: 'compound',
    equipment: [_Eq.dumbbell, _Eq.bench],
  ),
  _ExDef(
    name: 'Kabelzug-Flys',
    nameEn: 'Cable Fly',
    nameKey: 'cable_fly',
    instructions: 'Zwischen Kabelzügen stehen, Griffe in umarmender Bewegung zusammenführen.',
    instructionsEn: 'Stand between cable machines, bring handles together in a hugging motion.',
    muscleGroup: 'chest',
    category: 'isolation',
    equipment: [_Eq.cable, _Eq.chestFly],
  ),
  _ExDef(
    name: 'Maschinen-Brustpresse',
    nameEn: 'Machine Chest Press',
    nameKey: 'machine_chest_press',
    instructions: 'Aufrecht sitzen, Griffe nach vorn drücken bis Arme gestreckt sind.',
    instructionsEn: 'Sit upright, press handles forward until arms are fully extended.',
    muscleGroup: 'chest',
    category: 'compound',
    equipment: [_Eq.machine],
  ),
  _ExDef(
    name: 'Liegestütze',
    nameEn: 'Push-ups',
    nameKey: 'push_ups',
    instructions: 'Hände schulterbreit aufsetzen, Brust zum Boden senken und hochdrücken.',
    instructionsEn: 'Place hands shoulder-width apart, lower chest to floor and push up.',
    muscleGroup: 'chest',
    category: 'compound',
    equipment: [_Eq.bodyweight],
    trackWeight: false,
  ),

  // Rücken (6)
  _ExDef(
    name: 'Langhantel-Rudern',
    nameEn: 'Barbell Row',
    nameKey: 'barbell_row',
    instructions: 'An der Hüfte beugen, Langhantel zur unteren Brust ziehen, Schulterblätter zusammendrücken.',
    instructionsEn: 'Hinge at hips, pull barbell to lower chest, squeeze shoulder blades together.',
    muscleGroup: 'back',
    category: 'compound',
    equipment: [_Eq.barbell],
  ),
  _ExDef(
    name: 'Latzug',
    nameEn: 'Lat Pulldown',
    nameKey: 'lat_pulldown',
    instructions: 'Stange breit greifen, zur oberen Brust herunterziehen, leicht zurücklehnen.',
    instructionsEn: 'Grip bar wide, pull down to upper chest, lean back slightly.',
    muscleGroup: 'back',
    category: 'compound',
    equipment: [_Eq.cable, _Eq.latPulldown],
  ),
  _ExDef(
    name: 'Kabelrudern sitzend',
    nameEn: 'Seated Cable Row',
    nameKey: 'seated_cable_row',
    instructions: 'Aufrecht sitzen, Griff zur unteren Brust ziehen, Schulterblätter zusammenpressen.',
    instructionsEn: 'Sit upright, pull handle to lower chest, squeeze shoulder blades together.',
    muscleGroup: 'back',
    category: 'compound',
    equipment: [_Eq.cable, _Eq.seatedRow],
  ),
  _ExDef(
    name: 'Kurzhantel-Rudern',
    nameEn: 'Dumbbell Row',
    nameKey: 'dumbbell_row',
    instructions: 'Eine Hand auf Bank stützen, Kurzhantel mit der anderen Hand zur Hüfte ziehen.',
    instructionsEn: 'Brace one hand on bench, pull dumbbell to hip with the other hand.',
    muscleGroup: 'back',
    category: 'compound',
    equipment: [_Eq.dumbbell, _Eq.bench],
  ),
  _ExDef(
    name: 'Klimmzüge',
    nameEn: 'Pull-ups',
    nameKey: 'pull_ups',
    instructions: 'An Stange hängen im Obergriff, Kinn über die Stange ziehen.',
    instructionsEn: 'Hang from bar with overhand grip, pull chin above the bar.',
    muscleGroup: 'back',
    category: 'compound',
    equipment: [_Eq.bodyweight, _Eq.pullUpBar],
    trackWeight: false,
  ),
  _ExDef(
    name: 'T-Bar-Rudern',
    nameEn: 'T-Bar Row',
    nameKey: 't_bar_row',
    instructions: 'Über der Stange stehen, Griff zur Brust ziehen, Rücken gerade halten.',
    instructionsEn: 'Straddle the bar, pull handle to chest, keep back straight.',
    muscleGroup: 'back',
    category: 'compound',
    equipment: [_Eq.barbell],
  ),

  // Schultern (5)
  _ExDef(
    name: 'Schulterdrücken',
    nameEn: 'Overhead Press',
    nameKey: 'overhead_press',
    instructions: 'Stange auf Schulterhöhe, über Kopf drücken bis zur Streckung.',
    instructionsEn: 'Bar at shoulder height, press overhead to full extension.',
    muscleGroup: 'shoulders',
    category: 'compound',
    equipment: [_Eq.barbell],
  ),
  _ExDef(
    name: 'Seitheben',
    nameEn: 'Lateral Raise',
    nameKey: 'lateral_raise',
    instructions: 'Kurzhanteln seitlich heben bis Arme parallel zum Boden.',
    instructionsEn: 'Raise dumbbells to the sides until arms are parallel to the floor.',
    muscleGroup: 'shoulders',
    category: 'isolation',
    equipment: [_Eq.dumbbell],
  ),
  _ExDef(
    name: 'Frontheben',
    nameEn: 'Front Raise',
    nameKey: 'front_raise',
    instructions: 'Kurzhanteln vor dem Körper bis Schulterhöhe heben, langsam senken.',
    instructionsEn: 'Raise dumbbells in front to shoulder height, lower slowly.',
    muscleGroup: 'shoulders',
    category: 'isolation',
    equipment: [_Eq.dumbbell],
  ),
  _ExDef(
    name: 'Face Pull',
    nameEn: 'Face Pull',
    nameKey: 'face_pull',
    instructions: 'Seilgriff auf Gesichtshöhe ziehen, Hände auseinanderführen.',
    instructionsEn: 'Pull rope attachment to face height, spread hands apart.',
    muscleGroup: 'shoulders',
    category: 'isolation',
    equipment: [_Eq.cable],
  ),
  _ExDef(
    name: 'Maschinen-Schulterdrücken',
    nameEn: 'Machine Shoulder Press',
    nameKey: 'machine_shoulder_press',
    instructions: 'Aufrecht sitzen, Griffe über Kopf drücken bis zur vollen Streckung.',
    instructionsEn: 'Sit upright, press handles overhead to full extension.',
    muscleGroup: 'shoulders',
    category: 'compound',
    equipment: [_Eq.machine, _Eq.shoulderPress],
  ),

  // Bizeps (4)
  _ExDef(
    name: 'Langhantel-Curls',
    nameEn: 'Barbell Curl',
    nameKey: 'barbell_curl',
    instructions: 'Stange auf Oberschenkelhöhe, hochcurlen, Ellbogen fixiert halten.',
    instructionsEn: 'Bar at thigh height, curl up, keep elbows fixed.',
    muscleGroup: 'biceps',
    category: 'isolation',
    equipment: [_Eq.barbell],
  ),
  _ExDef(
    name: 'Kurzhantel-Curls',
    nameEn: 'Dumbbell Curl',
    nameKey: 'dumbbell_curl',
    instructions: 'Abwechselnd Kurzhanteln mit Untergriff curlen.',
    instructionsEn: 'Alternately curl dumbbells with underhand grip.',
    muscleGroup: 'biceps',
    category: 'isolation',
    equipment: [_Eq.dumbbell],
  ),
  _ExDef(
    name: 'Hammer-Curls',
    nameEn: 'Hammer Curl',
    nameKey: 'hammer_curl',
    instructions: 'Kurzhanteln mit neutralem Griff curlen, trainiert den Brachialis.',
    instructionsEn: 'Curl dumbbells with neutral grip, targets the brachialis.',
    muscleGroup: 'biceps',
    category: 'isolation',
    equipment: [_Eq.dumbbell],
  ),
  _ExDef(
    name: 'Kabelzug-Curls',
    nameEn: 'Cable Curl',
    nameKey: 'cable_curl',
    instructions: 'Kabelaufsatz von unten curlen, Ellbogen fixiert halten.',
    instructionsEn: 'Curl cable attachment from below, keep elbows fixed.',
    muscleGroup: 'biceps',
    category: 'isolation',
    equipment: [_Eq.cable],
  ),

  // Trizeps (4)
  _ExDef(
    name: 'Trizepsdrücken am Kabel',
    nameEn: 'Tricep Pushdown',
    nameKey: 'tricep_pushdown',
    instructions: 'Kabelstange nach unten drücken bis Arme voll gestreckt.',
    instructionsEn: 'Push cable bar down until arms are fully extended.',
    muscleGroup: 'triceps',
    category: 'isolation',
    equipment: [_Eq.cable],
  ),
  _ExDef(
    name: 'Trizepsdrücken über Kopf',
    nameEn: 'Overhead Tricep Extension',
    nameKey: 'overhead_tricep_extension',
    instructions: 'Kurzhantel über Kopf halten, hinter dem Kopf senken und wieder strecken.',
    instructionsEn: 'Hold dumbbell overhead, lower behind head and extend back up.',
    muscleGroup: 'triceps',
    category: 'isolation',
    equipment: [_Eq.dumbbell],
  ),
  _ExDef(
    name: 'Skull Crusher',
    nameEn: 'Skull Crusher',
    nameKey: 'skull_crusher',
    instructions: 'Auf Bank liegen, Stange zur Stirn senken und Arme strecken.',
    instructionsEn: 'Lie on bench, lower bar to forehead and extend arms.',
    muscleGroup: 'triceps',
    category: 'isolation',
    equipment: [_Eq.barbell, _Eq.bench],
  ),
  _ExDef(
    name: 'Dips',
    nameEn: 'Dips',
    nameKey: 'dips',
    instructions: 'Körper zwischen Parallelbarren senken, wieder hochdrücken bis zur Streckung.',
    instructionsEn: 'Lower body between parallel bars, push back up to full extension.',
    muscleGroup: 'triceps',
    category: 'compound',
    equipment: [_Eq.bodyweight, _Eq.dipStation],
  ),

  // Oberschenkel vorn (5)
  _ExDef(
    name: 'Kniebeuge',
    nameEn: 'Barbell Squat',
    nameKey: 'barbell_squat',
    instructions: 'Stange auf oberem Rücken, in die Hocke gehen, durch die Fersen hochdrücken.',
    instructionsEn: 'Bar on upper back, squat down, drive up through heels.',
    muscleGroup: 'quadriceps',
    category: 'compound',
    equipment: [_Eq.barbell],
  ),
  _ExDef(
    name: 'Beinpresse',
    nameEn: 'Leg Press',
    nameKey: 'leg_press',
    instructions: 'Füße schulterbreit auf Plattform, Schlitten auf 90 Grad senken und hochdrücken.',
    instructionsEn: 'Feet shoulder-width on platform, lower sled to 90 degrees and press up.',
    muscleGroup: 'quadriceps',
    category: 'compound',
    equipment: [_Eq.machine],
  ),
  _ExDef(
    name: 'Beinstrecken',
    nameEn: 'Leg Extension',
    nameKey: 'leg_extension',
    instructions: 'Beine gegen das Polster strecken bis gerade, langsam senken.',
    instructionsEn: 'Extend legs against the pad until straight, lower slowly.',
    muscleGroup: 'quadriceps',
    category: 'isolation',
    equipment: [_Eq.machine, _Eq.legExtension],
  ),
  _ExDef(
    name: 'Ausfallschritte',
    nameEn: 'Lunges',
    nameKey: 'lunges',
    instructions: 'Schritt nach vorn, hinteres Knie Richtung Boden senken, zurückdrücken.',
    instructionsEn: 'Step forward, lower back knee toward floor, push back up.',
    muscleGroup: 'quadriceps',
    category: 'compound',
    equipment: [_Eq.dumbbell, _Eq.bodyweight],
  ),
  _ExDef(
    name: 'Frontkniebeuge',
    nameEn: 'Front Squat',
    nameKey: 'front_squat',
    instructions: 'Stange auf vorderer Schulter, Kniebeuge mit aufrechtem Oberkörper.',
    instructionsEn: 'Bar on front shoulders, squat with upright torso.',
    muscleGroup: 'quadriceps',
    category: 'compound',
    equipment: [_Eq.barbell],
  ),

  // Oberschenkel hinten (4)
  _ExDef(
    name: 'Rumänisches Kreuzheben',
    nameEn: 'Romanian Deadlift',
    nameKey: 'romanian_deadlift',
    instructions: 'An der Hüfte beugen mit leicht gebeugten Knien, Stange entlang der Beine senken.',
    instructionsEn: 'Hinge at hips with slightly bent knees, lower bar along the legs.',
    muscleGroup: 'hamstrings',
    category: 'compound',
    equipment: [_Eq.barbell],
  ),
  _ExDef(
    name: 'Beinbeuger',
    nameEn: 'Leg Curl',
    nameKey: 'leg_curl',
    instructions: 'Bäuchlings liegen, Polster Richtung Gesäß curlen und langsam senken.',
    instructionsEn: 'Lie face down, curl pad toward glutes and lower slowly.',
    muscleGroup: 'hamstrings',
    category: 'isolation',
    equipment: [_Eq.machine, _Eq.legCurl],
  ),
  _ExDef(
    name: 'Good Morning',
    nameEn: 'Good Morning',
    nameKey: 'good_morning',
    instructions: 'Stange auf Rücken, an der Hüfte nach vorn beugen, Rücken gerade halten.',
    instructionsEn: 'Bar on back, hinge forward at hips, keep back straight.',
    muscleGroup: 'hamstrings',
    category: 'compound',
    equipment: [_Eq.barbell],
  ),
  _ExDef(
    name: 'Nordic Curl',
    nameEn: 'Nordic Curl',
    nameKey: 'nordic_curl',
    instructions: 'Knien mit fixierten Füßen, Körper kontrolliert nach vorn senken.',
    instructionsEn: 'Kneel with feet anchored, lower body forward in a controlled manner.',
    muscleGroup: 'hamstrings',
    category: 'isolation',
    equipment: [_Eq.bodyweight],
    trackWeight: false,
  ),

  // Gesäß (3)
  _ExDef(
    name: 'Hip Thrust',
    nameEn: 'Hip Thrust',
    nameKey: 'hip_thrust',
    instructions: 'Rücken an Bank, Hüfte mit Stange auf dem Schoß nach oben drücken.',
    instructionsEn: 'Back against bench, drive hips up with barbell across lap.',
    muscleGroup: 'glutes',
    category: 'compound',
    equipment: [_Eq.barbell, _Eq.bench],
  ),
  _ExDef(
    name: 'Kabelzug-Kickback',
    nameEn: 'Cable Kickback',
    nameKey: 'cable_kickback',
    instructions: 'Fußmanschette anlegen, Bein gegen Kabelwiderstand nach hinten strecken.',
    instructionsEn: 'Attach ankle cuff, extend leg back against cable resistance.',
    muscleGroup: 'glutes',
    category: 'isolation',
    equipment: [_Eq.cable],
  ),
  _ExDef(
    name: 'Glute Bridge',
    nameEn: 'Glute Bridge',
    nameKey: 'glute_bridge',
    instructions: 'Flach liegen, Hüfte nach oben drücken, Gesäß oben anspannen.',
    instructionsEn: 'Lie flat, drive hips up, squeeze glutes at the top.',
    muscleGroup: 'glutes',
    category: 'isolation',
    equipment: [_Eq.bodyweight],
    trackWeight: false,
  ),

  // Waden (2)
  _ExDef(
    name: 'Wadenheben stehend',
    nameEn: 'Standing Calf Raise',
    nameKey: 'standing_calf_raise',
    instructions: 'Unter Last auf die Zehenspitzen steigen, langsam senken für volle Dehnung.',
    instructionsEn: 'Rise onto toes under load, lower slowly for full stretch.',
    muscleGroup: 'calves',
    category: 'isolation',
    equipment: [_Eq.machine, _Eq.smithMachine],
  ),
  _ExDef(
    name: 'Wadenheben sitzend',
    nameEn: 'Seated Calf Raise',
    nameKey: 'seated_calf_raise',
    instructions: 'Sitzen mit Polster auf den Knien, Fersen so hoch wie möglich heben.',
    instructionsEn: 'Sit with pad on knees, raise heels as high as possible.',
    muscleGroup: 'calves',
    category: 'isolation',
    equipment: [_Eq.machine],
  ),

  // Rumpf (4)
  _ExDef(
    name: 'Plank',
    nameEn: 'Plank',
    nameKey: 'plank',
    instructions: 'Liegestützposition auf Unterarmen halten, Körper gerade halten.',
    instructionsEn: 'Hold push-up position on forearms, keep body straight.',
    muscleGroup: 'core',
    category: 'isolation',
    equipment: [_Eq.bodyweight],
    trackWeight: false,
  ),
  _ExDef(
    name: 'Crunches am Halbball',
    nameEn: 'Bosu Ball Crunch',
    nameKey: 'bosu_crunch',
    instructions: 'Rücken auf dem Halbball (Bosu Ball), Bauchmuskeln anspannen und Oberkörper aufrollen.',
    instructionsEn: 'Back on Bosu ball, engage abs and curl upper body up.',
    muscleGroup: 'core',
    category: 'isolation',
    equipment: [_Eq.bodyweight],
    trackWeight: false,
  ),
  _ExDef(
    name: 'Beinheben hängend',
    nameEn: 'Hanging Leg Raise',
    nameKey: 'hanging_leg_raise',
    instructions: 'An Stange hängen, Beine bis zur Horizontalen oder höher heben.',
    instructionsEn: 'Hang from bar, raise legs to horizontal or higher.',
    muscleGroup: 'core',
    category: 'isolation',
    equipment: [_Eq.bodyweight, _Eq.pullUpBar],
    trackWeight: false,
  ),
  _ExDef(
    name: 'Ab Rollout',
    nameEn: 'Ab Rollout',
    nameKey: 'ab_rollout',
    instructions: 'Knien mit Ab-Wheel, nach vorn rollen und mit der Rumpfmuskulatur zurückziehen.',
    instructionsEn: 'Kneel with ab wheel, roll forward and pull back using core muscles.',
    muscleGroup: 'core',
    category: 'isolation',
    equipment: [_Eq.bodyweight],
    trackWeight: false,
  ),

  // Ganzkörper (3)
  _ExDef(
    name: 'Kreuzheben',
    nameEn: 'Deadlift',
    nameKey: 'deadlift',
    instructions: 'Stange über Fußmitte, beugen und greifen, bis zur Streckung hochziehen.',
    instructionsEn: 'Bar over mid-foot, bend and grip, pull up to full extension.',
    muscleGroup: 'fullBody',
    category: 'compound',
    equipment: [_Eq.barbell],
  ),
  _ExDef(
    name: 'Umsetzen & Drücken',
    nameEn: 'Clean & Press',
    nameKey: 'clean_and_press',
    instructions: 'Stange explosiv zu den Schultern umsetzen, dann über Kopf drücken.',
    instructionsEn: 'Explosively clean bar to shoulders, then press overhead.',
    muscleGroup: 'fullBody',
    category: 'compound',
    equipment: [_Eq.barbell],
  ),
  _ExDef(
    name: 'Farmers Walk',
    nameEn: "Farmer's Walk",
    nameKey: 'farmers_walk',
    instructions: 'Schwere Kurzhanteln seitlich halten, mit aufrechter Haltung gehen.',
    instructionsEn: 'Hold heavy dumbbells at sides, walk with upright posture.',
    muscleGroup: 'fullBody',
    category: 'compound',
    equipment: [_Eq.dumbbell],
  ),

  // Unterarme (2)
  _ExDef(
    name: 'Handgelenkscurls',
    nameEn: 'Wrist Curl',
    nameKey: 'wrist_curl',
    instructions: 'Unterarme auf Bank ablegen, Handgelenke mit der Stange nach oben curlen.',
    instructionsEn: 'Rest forearms on bench, curl wrists upward with the bar.',
    muscleGroup: 'forearms',
    category: 'isolation',
    equipment: [_Eq.barbell, _Eq.bench],
  ),
  _ExDef(
    name: 'Reverse Curls',
    nameEn: 'Reverse Curl',
    nameKey: 'reverse_curl',
    instructions: 'Stange im Obergriff greifen und mit fixierten Ellbogen curlen.',
    instructionsEn: 'Grip bar with overhand grip and curl with fixed elbows.',
    muscleGroup: 'forearms',
    category: 'isolation',
    equipment: [_Eq.barbell],
  ),

  // Zusätzliche Übungen
  _ExDef(
    name: 'Bulgarische Kniebeuge',
    nameEn: 'Bulgarian Split Squat',
    nameKey: 'bulgarian_split_squat',
    instructions: 'Hinterer Fuß auf Bank ablegen, vorderes Bein in die Hocke gehen.',
    instructionsEn: 'Rear foot on bench, squat down on front leg.',
    muscleGroup: 'quadriceps',
    category: 'compound',
    equipment: [_Eq.dumbbell, _Eq.bodyweight, _Eq.bench],
  ),
  _ExDef(
    name: 'Latzug eng',
    nameEn: 'Close Grip Lat Pulldown',
    nameKey: 'close_grip_lat_pulldown',
    instructions: 'Enge Griffstange am Latzug zur oberen Brust herunterziehen.',
    instructionsEn: 'Pull close-grip bar down to upper chest on lat pulldown.',
    muscleGroup: 'back',
    category: 'compound',
    equipment: [_Eq.cable, _Eq.latPulldown],
  ),
  _ExDef(
    name: 'Reverse Fly',
    nameEn: 'Reverse Fly',
    nameKey: 'reverse_fly',
    instructions: 'Vorgebeugt stehend, Kurzhanteln seitlich nach oben heben.',
    instructionsEn: 'Bent over, raise dumbbells to the sides.',
    muscleGroup: 'shoulders',
    category: 'isolation',
    equipment: [_Eq.dumbbell],
  ),
  _ExDef(
    name: 'Kabel-Seitheben',
    nameEn: 'Cable Lateral Raise',
    nameKey: 'cable_lateral_raise',
    instructions: 'Am Kabelzug seitlich stehend, Arm seitlich bis Schulterhöhe heben.',
    instructionsEn: 'Stand sideways at cable, raise arm to the side to shoulder height.',
    muscleGroup: 'shoulders',
    category: 'isolation',
    equipment: [_Eq.cable],
  ),
  _ExDef(
    name: 'Brustdips',
    nameEn: 'Chest Dips',
    nameKey: 'chest_dips',
    instructions: 'Körper am Barren nach vorn neigen, tief senken und hochdrücken.',
    instructionsEn: 'Lean forward on parallel bars, lower deep and push back up.',
    muscleGroup: 'chest',
    category: 'compound',
    equipment: [_Eq.bodyweight, _Eq.dipStation],
  ),
  _ExDef(
    name: 'Hackenschmidt-Kniebeuge',
    nameEn: 'Hack Squat',
    nameKey: 'hack_squat',
    instructions: 'An der Hackenschmidt-Maschine Schlitten nach oben drücken.',
    instructionsEn: 'Press sled upward on the hack squat machine.',
    muscleGroup: 'quadriceps',
    category: 'compound',
    equipment: [_Eq.machine],
  ),

  // Ausdauer (4)
  _ExDef(
    name: 'Laufband',
    nameEn: 'Treadmill Run',
    nameKey: 'treadmill_run',
    instructions: 'In gleichmäßigem Tempo auf dem Laufband laufen.',
    instructionsEn: 'Run on the treadmill at a steady pace.',
    muscleGroup: 'cardio',
    category: 'cardio',
    equipment: [_Eq.treadmill],
    trackWeight: false,
  ),
  _ExDef(
    name: 'Rudergerät',
    nameEn: 'Rowing Machine',
    nameKey: 'rowing_machine',
    instructions: 'Zuerst mit den Beinen drücken, dann Griff zur unteren Brust ziehen.',
    instructionsEn: 'Drive with legs first, then pull handle to lower chest.',
    muscleGroup: 'cardio',
    category: 'cardio',
    equipment: [_Eq.rowingMachine],
    trackWeight: false,
  ),
  _ExDef(
    name: 'Ergometer',
    nameEn: 'Stationary Bike',
    nameKey: 'stationary_bike',
    instructions: 'Mit gleichmäßiger Trittfrequenz und angemessenem Widerstand treten.',
    instructionsEn: 'Pedal at a steady cadence with appropriate resistance.',
    muscleGroup: 'cardio',
    category: 'cardio',
    equipment: [_Eq.stationaryBike],
    trackWeight: false,
  ),
  _ExDef(
    name: 'Crosstrainer',
    nameEn: 'Elliptical',
    nameKey: 'elliptical',
    instructions: 'Gleichmäßig auf dem Crosstrainer bei moderater Intensität trainieren.',
    instructionsEn: 'Train steadily on the elliptical at moderate intensity.',
    muscleGroup: 'cardio',
    category: 'cardio',
    equipment: [_Eq.elliptical],
    trackWeight: false,
  ),

  // Neue Übungen — Bank, Dip-Station, Klimmzugstange, etc.
  _ExDef(
    name: 'Schrägbank-Kurzhanteldrücken',
    nameEn: 'Incline Dumbbell Press',
    nameKey: 'incline_dumbbell_press',
    instructions: 'Schrägbank auf 30-45 Grad, Kurzhanteln von Brusthöhe nach oben drücken.',
    instructionsEn: 'Incline bench at 30-45 degrees, press dumbbells up from chest height.',
    muscleGroup: 'chest',
    category: 'compound',
    equipment: [_Eq.dumbbell, _Eq.inclineBench],
  ),
  _ExDef(
    name: 'Kurzhantel-Flys',
    nameEn: 'Dumbbell Fly',
    nameKey: 'dumbbell_fly',
    instructions: 'Flach auf Bank liegen, Kurzhanteln in weitem Bogen zusammenführen.',
    instructionsEn: 'Lie flat on bench, bring dumbbells together in a wide arc.',
    muscleGroup: 'chest',
    category: 'isolation',
    equipment: [_Eq.dumbbell, _Eq.bench],
  ),
  _ExDef(
    name: 'Schrägbank-Flys',
    nameEn: 'Incline Dumbbell Fly',
    nameKey: 'incline_dumbbell_fly',
    instructions: 'Schrägbank auf 30 Grad, Kurzhanteln in umarmender Bewegung zusammenführen.',
    instructionsEn: 'Incline bench at 30 degrees, bring dumbbells together in a hugging motion.',
    muscleGroup: 'chest',
    category: 'isolation',
    equipment: [_Eq.dumbbell, _Eq.inclineBench],
  ),
  _ExDef(
    name: 'Negativbankdrücken',
    nameEn: 'Decline Bench Press',
    nameKey: 'decline_bench_press',
    instructions: 'Bank leicht nach unten geneigt, Stange zur unteren Brust senken und drücken.',
    instructionsEn: 'Bench slightly declined, lower bar to lower chest and press up.',
    muscleGroup: 'chest',
    category: 'compound',
    equipment: [_Eq.barbell, _Eq.bench],
  ),
  _ExDef(
    name: 'Preacher Curls',
    nameEn: 'Preacher Curl',
    nameKey: 'preacher_curl',
    instructions: 'Arme auf Preacher-Bank ablegen, Stange oder Kurzhantel kontrolliert curlen.',
    instructionsEn: 'Rest arms on preacher bench, curl bar or dumbbell in a controlled manner.',
    muscleGroup: 'biceps',
    category: 'isolation',
    equipment: [_Eq.barbell, _Eq.preacherCurlBench],
  ),
  _ExDef(
    name: 'Konzentrationscurls',
    nameEn: 'Concentration Curl',
    nameKey: 'concentration_curl',
    instructions: 'Sitzend, Ellbogen an der Innenseite des Oberschenkels abstützen, Kurzhantel curlen.',
    instructionsEn: 'Seated, brace elbow against inner thigh, curl dumbbell.',
    muscleGroup: 'biceps',
    category: 'isolation',
    equipment: [_Eq.dumbbell, _Eq.bench],
  ),
  _ExDef(
    name: 'Arnold Press',
    nameEn: 'Arnold Press',
    nameKey: 'arnold_press',
    instructions: 'Kurzhanteln vor dem Gesicht halten, beim Hochdrücken Hände nach außen rotieren.',
    instructionsEn: 'Hold dumbbells in front of face, rotate hands outward while pressing up.',
    muscleGroup: 'shoulders',
    category: 'compound',
    equipment: [_Eq.dumbbell, _Eq.bench],
  ),
  _ExDef(
    name: 'Hyperextensions',
    nameEn: 'Hyperextension',
    nameKey: 'hyperextension',
    instructions: 'Bäuchlings auf der Hyperextension-Bank, Oberkörper senken und kontrolliert aufrichten.',
    instructionsEn: 'Face down on hyperextension bench, lower upper body and raise back up in a controlled manner.',
    muscleGroup: 'back',
    category: 'isolation',
    equipment: [_Eq.hyperextensionBench],
  ),
  _ExDef(
    name: 'Kabelzug-Crunch',
    nameEn: 'Cable Crunch',
    nameKey: 'cable_crunch',
    instructions: 'Knien vor dem Kabelzug, Seilgriff hinter dem Kopf halten und einrollen.',
    instructionsEn: 'Kneel in front of cable, hold rope behind head and crunch down.',
    muscleGroup: 'core',
    category: 'isolation',
    equipment: [_Eq.cable],
    trackWeight: false,
  ),
  _ExDef(
    name: 'Enges Bankdrücken',
    nameEn: 'Close Grip Bench Press',
    nameKey: 'close_grip_bench_press',
    instructions: 'Enger Griff an der Langhantel, Stange zur unteren Brust senken und drücken.',
    instructionsEn: 'Narrow grip on barbell, lower bar to lower chest and press up.',
    muscleGroup: 'triceps',
    category: 'compound',
    equipment: [_Eq.barbell, _Eq.bench],
  ),
  _ExDef(
    name: 'Trizeps-Kickbacks',
    nameEn: 'Tricep Kickback',
    nameKey: 'tricep_kickback',
    instructions: 'Vorgebeugt, Oberarm fixiert, Kurzhantel nach hinten strecken.',
    instructionsEn: 'Bent over, upper arm fixed, extend dumbbell backward.',
    muscleGroup: 'triceps',
    category: 'isolation',
    equipment: [_Eq.dumbbell, _Eq.bench],
  ),
  _ExDef(
    name: 'Sumo-Kreuzheben',
    nameEn: 'Sumo Deadlift',
    nameKey: 'sumo_deadlift',
    instructions: 'Weiter Stand, Stange mit engem Griff zwischen den Beinen hochziehen.',
    instructionsEn: 'Wide stance, pull bar up with narrow grip between legs.',
    muscleGroup: 'fullBody',
    category: 'compound',
    equipment: [_Eq.barbell],
  ),
  _ExDef(
    name: 'Beinpresse eng',
    nameEn: 'Narrow Leg Press',
    nameKey: 'narrow_leg_press',
    instructions: 'Füße eng zusammen auf der Plattform, Schlitten kontrolliert senken und drücken.',
    instructionsEn: 'Feet close together on platform, lower sled in a controlled manner and press up.',
    muscleGroup: 'quadriceps',
    category: 'compound',
    equipment: [_Eq.machine],
  ),
  _ExDef(
    name: 'Adduktoren-Maschine',
    nameEn: 'Adductor Machine',
    nameKey: 'adductor_machine',
    instructions: 'Beine gegen Polster zusammenführen, langsam zurück in Ausgangsposition.',
    instructionsEn: 'Squeeze legs together against pads, slowly return to starting position.',
    muscleGroup: 'quadriceps',
    category: 'isolation',
    equipment: [_Eq.machine],
  ),
  _ExDef(
    name: 'Abduktoren-Maschine',
    nameEn: 'Abductor Machine',
    nameKey: 'abductor_machine',
    instructions: 'Beine gegen Polster auseinanderdrücken, kontrolliert zurück.',
    instructionsEn: 'Push legs apart against pads, return in a controlled manner.',
    muscleGroup: 'glutes',
    category: 'isolation',
    equipment: [_Eq.machine],
  ),
  _ExDef(
    name: 'Shrugs',
    nameEn: 'Shrugs',
    nameKey: 'shrugs',
    instructions: 'Kurzhanteln oder Langhantel halten, Schultern zu den Ohren hochziehen.',
    instructionsEn: 'Hold dumbbells or barbell, shrug shoulders up toward ears.',
    muscleGroup: 'back',
    category: 'isolation',
    equipment: [_Eq.dumbbell, _Eq.barbell],
  ),
];
